meta_product_name: "Product Name"
meta_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
